name: Sync Fork with Upstream

on:
  schedule:
    # Run once a day at midnight
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/maester365/maester.git

      - name: Fetch from upstream
        run: |
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main

      - name: Push changes
        run: |
          git push origin main